config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: :destroy
  resources :categories, except: :destroy
end

app/models/category.rb
class Category < ActiveRecord::Base
 has_many :post_categories
 has_many :posts, through: :post_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  validates :title, :url, :description , presence: true
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update]

  def index
    @categories = Category.all
  end

  def show

  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = 'Your category was created'
      redirect_to categories_path
    else
      @errors = @category.errors if @category.errors.any?
      render :new
    end
  end

  def edit

  end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Your category was updated'
      redirect_to categories_path
    else
      @errors = @category.errors if @category.errors.any?
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit!
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]

  def index
    @posts = Post.all
  end

  def show

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      flash[:notice] = "Your post was created"
      redirect_to posts_path
    else
      @errors = @post.errors if @post.errors.any?
      render :new
    end
  end

  def edit

  end

  def update

    if @post.update(post_params)
      flash[:notice] = "Your post was updated"
      redirect_to posts_path
    else
      @errors = @post.errors if @post.errors.any?
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit!
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= render 'shared/errors' %>

<%= form_for @category do |f| %>
    <div class="contol-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit 'Create Category', class: 'btn btn-primary' %>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<h3>Categories</h3>

<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category %></li>
  <% end %>
</ul>

<%= link_to 'New category', new_category_path %>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<h3><%= @category.name %></h3>

<%= link_to 'Edit', edit_category_path(@category) %>
<br/>
<%= link_to "Back to Categories", categories_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to 'link', '' %>
  </li>
</ul>
<div class = 'nav_item'>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
</div>
<div class = 'nav_item'>
  <%= link_to 'New Category', new_category_path, class: 'btn btn-success btn-small' %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors' %>

<%= form_for @post do |f| %>
    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>

    <%= f.submit 'Create Post', class: 'btn btn-primary' %>

<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<h3>Welcome!</h3>

<p>This is the Postit template. You've access the PostsController, index action. This is the index template. Find me under app/views/posts folder.</p>

<ul>
  <% @posts.each do |post| %>
      <li><%= link_to post.title, post %></li>
  <% end %>
</ul>

<%= link_to 'New post', new_post_path %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<br/>
URL: <%= @post.url %>
<br/>
Description: <%= @post.description %>
<br/>

<%= link_to 'Edit', edit_post_path(@post) %>
<br/>
<%= link_to 'Back to posts', posts_path %>

app/views/shared/_errors.html.erb
<% if @errors %>
    <div class="alert alert-error">
      <h5>There were these errors:</h5>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>